import "@/app/globals.css";
import Link from "next/link";
import { Toaster } from "react-hot-toast";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { createSupabaseForServerComponent } from "@/lib/supabase.server";
import SignOut from "@/components/SignOut";
import { env } from "@/lib/env.server";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	const supabase = createSupabaseForServerComponent();

	const {
		data: { user },
	} = await supabase.auth.getUser();

	return (
		<html lang="en">
			<body className={inter.className}>
				<nav className="flex-between w-full mb-16 pt-3">
					<Link href="/">
						<h1>B2B</h1>
					</Link>
					{user && (
						<div className="flex gap-4">
							<Link href="/business/new" className="outline_btn">
								Create a new business
							</Link>
							<SignOut />
						</div>
					)}
				</nav>
				<Toaster position="bottom-right" />
				{children}
				<Script
					src={`https://www.googletagmanager.com/gtag/js?id=${env.NEXT_PUBLIC_GA_MEASUREMENT_ID}`}
				/>
				<Script id="google-analytics">
					{`
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());
 
          gtag('config', '${env.NEXT_PUBLIC_GA_MEASUREMENT_ID}');
        `}
				</Script>
			</body>
		</html>
	);
}
